### ISSUE TITLE
Crash on "no blob"

### ISSUE THREAD

**Issue by clehner** [dominictarr/multiblob-http#1]
in scuttlebot with ssb-ws plugin, with patchbay as client:

```
GET /blobs/get/&qjeAs8+uMXLlyovT4JnEpMwTNDx/QXHfOl2nv2u0VCM=.sha256
GET /blobs/get/&qjeAs8+uMXLlyovT4JnEpMwTNDx/QXHfOl2nv2u0VCM=.sha256
GET /blobs/get/&Zm/6FJsLdopu3zD1Z9i+uUhzei+t5TFbJV9sseFWpMc=.sha256
GET /blobs/get/&Zm/6FJsLdopu3zD1Z9i+uUhzei+t5TFbJV9sseFWpMc=.sha256
Error: no blob:&qjeAs8+uMXLlyovT4JnEpMwTNDx/QXHfOl2nv2u0VCM=.sha256
    at /usr/local/src/ssb-ws/node_modules/multiblob-http/index.js:39:23
    at /usr/local/src/scuttlebot/node_modules/multiblob/index.js:141:15
    at continuation (/usr/local/src/scuttlebot/node_modules/cont/node_modules/continuable-para/node_modules/continuable-list/index.js:24:25)
    at /usr/local/src/scuttlebot/node_modules/multiblob/index.js:114:9
    at done (/usr/local/src/scuttlebot/node_modules/multiblob/index.js:41:38)
    at FSReqWrap.oncomplete (fs.js:82:15)
_http_outgoing.js:403
    throw new Error('Can\'t render headers after they are sent to the client.');
    ^

Error: Can't render headers after they are sent to the client.
    at ServerResponse.OutgoingMessage._renderHeaders (_http_outgoing.js:403:11)
    at ServerResponse.writeHead (_http_server.js:184:20)
    at /usr/local/src/ssb-ws/node_modules/multiblob-http/index.js:41:13
    at /usr/local/src/scuttlebot/node_modules/multiblob/index.js:141:15
    at continuation (/usr/local/src/scuttlebot/node_modules/cont/node_modules/continuable-para/node_modules/continuable-list/index.js:24:25)
    at /usr/local/src/scuttlebot/node_modules/multiblob/index.js:114:9
    at done (/usr/local/src/scuttlebot/node_modules/multiblob/index.js:41:38)
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by clehner** [comment]
duplicate of dominictarr/patchbay#50
