### ISSUE TITLE
SSB Server crash when using `blobs.size()`

### ISSUE THREAD

**Issue by timjrobinson** [dominictarr/multiblob-http#5]
Getting this with ssb-server master + ssb-ws latest. This is happening when connecting to `ws:/localhost:8989~shs:pPnZTDg8XedTXwgRqjMa5CGmDTwBTSuMzdqlAvNI8ck=` with https://github.com/arj03/ssb-browser-demo. No blobs are loading client side either, so could be something to do with the frontend. 

```
/home/tim/projects/ssb-server/node_modules/multiblob-http/index.js:62
      blobs.size(hash, function (err, size) {
            ^

TypeError: Cannot read property 'size' of undefined
    at /home/tim/projects/ssb-server/node_modules/multiblob-http/index.js:62:13
    at /home/tim/projects/ssb-server/node_modules/ssb-ws/blobs.js:36:15
    at /home/tim/projects/ssb-server/node_modules/ssb-blobs/inject.js:292:11
    at next (/home/tim/projects/ssb-server/node_modules/ssb-blobs/inject.js:170:7)
    at /home/tim/projects/ssb-server/node_modules/ssb-blobs/inject.js:159:13
    at /home/tim/projects/ssb-server/node_modules/multiblob/index.js:124:20
    at continuation (/home/tim/projects/ssb-server/node_modules/continuable-list/index.js:24:25)
    at /home/tim/projects/ssb-server/node_modules/multiblob/index.js:94:9
    at done (/home/tim/projects/ssb-server/node_modules/multiblob/util.js:88:38)
    at FSReqWrap.oncomplete (fs.js:154:5)
```

Investigating root cause now.

**Comment by timjrobinson** [comment]
I didn't have `ssb-blobs` plugin enabled. I thought that would have been auto-added with something I installed or default server config. Fixed with changing secret-stack setup to:

```
.use(require('ssb-blobs'))
.use(require('ssb-ws'))
```

Could use a better error message on load saying ssb-blobs is required and isn't enabled. Can close for now.
